### PR TITLE
Modified table name in login page

### PR DESCRIPTION
**Pull request by Bhola-B2C**
The table name was incorrect in login.php It should be register instead of login!!!

### CODE REVIEW

**Review by shivhek25 — CHANGES_REQUESTED** [review]
1. Is it working now ? 
2. I don't have  a table called 'register' so how can I select from that table ?
3. Why isn't mysqli_num_rows() in line 12 highlighted in blue as mysqli_query() in line 11 ?

**Comment by Bhola-B2C** [comment]
But in register.php you are inserting data into register table

**Comment by shivhek25** [comment]
Okay, forgot that. 
What about 3 ?

**Comment by Bhola-B2C** [comment]
in your code u wrote mysql_num_rows() instead of mysqli
this may be the problem

**Comment by shivhek25** [comment]
Yes, I wrote that because mysqli_num_rows() wasn't working

**Comment by Bhola-B2C** [comment]
now it will work
the problem was that ur query was returning false value

**Comment by shivhek25** [comment]
Wow. Great, thanks

**Pull request merged**
